name: Prebuild Codespaces

on:
  push:

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: github/codespaces-precache@v1-stable
        with:
          regions: WestUs2 EastUs WestEurope
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
